# see config.go "type Config" for more fields
clientid:
clientsecret:
bottoken:
adminuser:
errorlog: ""
backlog_limit: 200
http:
  listen: "localhost:2202"
  public: "https://home.riking.org"
statusmessage: "in the garbage"
