#create a bot to obtain tokens: https://discordapp.com/developers/applications/ 
clientid:
clientsecret:
bottoken:
errorlog:
adminuser:
shards: 1 #needs at least one shard
statusmsg: "in the garbage"
http: #used for public oauth
  listen: "localhost:2202"
  public: "https://example.com"

